repos:
  - repo: https://github.com/econchick/interrogate
    rev: 1.3.1
    hooks:
      - id: interrogate
        args: [-v, --fail-under=80, --ignore-private, --ignore-init-method, --ignore-init-module, --ignore-magic, --ignore-property-decorators, --ignore-module]
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        args: [--max-line-length=88]  # default line length for black