name: Build and publish documentation

on:
  push:
    branches: [documentation]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'documentation'
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - name: Extract docstrings
      run: |
        poetry run docster local docster -o docs/docs/docster.md -m file
    - name: Publish documentation
      env:
        GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
        GIT_USER: ${{ github.actor }}
      working-directory: ./docs
      run: |
        yarn install
        yarn deploy