name: Linting and tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install
    - name: Check formatting with black
      run: |
        poetry run black . --check
    - name: Lint with flake8
      run: |
        poetry run flake8 .
    - name: Check docstring coverage with interrogate
      run: |
        poetry run interrogate docster --generate-badge docs-badge.svg
    - name: Run tests with pytest
      run: |
        poetry run pytest --cov docster tests/ --doctest-modules --junitxml=junit/test-results-${{ matrix.python-version }}.xml
    - name: Upload pytest test results
      uses: actions/upload-artifact@v2
      with:
        name: pytest-results-${{ matrix.python-version }}
        path: junit/test-results-${{ matrix.python-version }}.xml
